< ../config.mk

all:V: bin/targets
	$prereq | xargs mk

results/$nPOP$POP1"_ALL."%".phase3_bc_union.20130502.biallelic_svm_snps_indelsAF0.005_svs.gl.vcf.gz":Q:	data/1000G/vcfs/ALL.%.phase3_bc_union.20130502.biallelic_svm_snps_indelsAF0.005_svs.gl.vcf.gz
	bin/0.vcf_population_sampler.sh $POP1 &&
	mv tmp/$POP1"_sample.list.build" results/$POP1"_sample.list" &&
	bin/1b.vcf_slicer.sh $prereq $POP1 $target &&
	mv $target.build $target &&
	rm tmp/*
