< ../config.mk

all:VQ: bin/targets
	$prereq | xargs mk

results/chr%.$POP3.$POP2.ml:Q:
	chromosome=$(echo $target | sed s#results/##g | cut -d"." -f1)
	pop3_file=$(ls data/POP3/*$chromosome*.saf.idx)
	pop2_file=$(ls data/POP2/*$chromosome*.saf.idx)
	echo "calculating $target"
	echo "using $pop3_file vs $pop2_file"
	echo "and $nth_2dSFS threads"
## REPLACE bellow with path to realSFS
	realSFS $pop3_file $pop2_file -P $nth_2dSFS > $target.build &&
	mv $target.build $target

