< ../config.mk

all:V: bin/targets
	$prereq | xargs mk

results/$nPOP$POP2"_ALL."%".phase3_bc_union.20130502.biallelic_svm_snps_indelsAF0.005_svs.gl.vcf.gz":Q: data/1000G/vcfs/ALL.%.phase3_bc_union.20130502.biallelic_svm_snps_indelsAF0.005_svs.gl.vcf.gz
        bin/0.vcf_population_sampler.sh $POP2 &&
        mv tmp/$POP2"_sample.list.build" results/$POP2"_sample.list" &&
        bin/1b.vcf_slicer.sh $prereq $POP2 $target &&
        mv $target.build $target &&
        rm tmp/*
